version: "3.9"
   
services:
  db:
    image: postgres
    env_file:
      - .env

  web:
    image: public.ecr.aws/w0f5g4k6/javaweb:latest
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: 
      - .env